import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  ArrowLeft,
  Shield,
  AlertTriangle,
  Clock,
  Server,
  Brain,
  Target,
  Eye,
  Lightbulb,
  TrendingUp,
  CheckCircle,
  XCircle,
  FileWarning,
} from 'lucide-react';
import { reportsApi } from '@/lib/api';
import type { ThreatReport } from '@/types';
import { formatDate, getSeverityColor, getSeverityIcon, getRiskScoreColor } from '@/lib/utils';

export default function ReportDetail() {
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<ThreatReport | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadReport();
  }, [id]);

  const loadReport = async () => {
    if (!id) return;
    try {
      const data = await reportsApi.getById(parseInt(id));
      setReport(data);
    } catch (error) {
      console.error('Failed to load report:', error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-center">
          <Brain className="w-12 h-12 text-info animate-pulse mx-auto mb-4" />
          <p className="text-gray-400">Analyzing threat intelligence...</p>
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-center">
          <FileWarning className="w-16 h-16 text-gray-600 mx-auto mb-4" />
          <p className="text-gray-400">Report not found</p>
          <Link to="/" className="text-info hover:text-info-light mt-4 inline-block">
            Return to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-8 max-w-[1600px] mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <Link
            to="/"
            className="p-2 hover:bg-dark-hover rounded-lg transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h1 className="text-3xl font-bold text-white mb-2">
              Threat Report #{report.id.toString().padStart(4, '0')}
            </h1>
            <p className="text-gray-400">Generated by AI-powered threat analysis</p>
          </div>
        </div>
        <span
          className={`inline-flex items-center px-4 py-2 rounded-lg text-sm font-medium border ${getSeverityColor(
            report.severity
          )}`}
        >
          {getSeverityIcon(report.severity)} {report.severity} Severity
        </span>
      </div>

      {/* TL;DR - AI Summary */}
      {report.details?.tldr && (
        <div className="bg-gradient-to-r from-info/10 to-info/5 border border-info/20 rounded-lg p-6">
          <div className="flex items-start space-x-4">
            <div className="p-3 bg-info/10 rounded-lg">
              <Brain className="w-6 h-6 text-info" />
            </div>
            <div className="flex-1">
              <h3 className="text-lg font-semibold text-white mb-2">
                AI-Generated Executive Summary
              </h3>
              <p className="text-gray-200 leading-relaxed">{report.details.tldr}</p>
            </div>
          </div>
        </div>
      )}

      {/* Key Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-dark-card border border-dark-border rounded-lg p-6">
          <div className="flex items-center space-x-3 mb-2">
            <Target className="w-5 h-5 text-critical" />
            <h3 className="text-sm font-medium text-gray-400">Risk Score</h3>
          </div>
          <p className={`text-3xl font-bold ${getRiskScoreColor(report.risk_score)}`}>
            {report.risk_score}/100
          </p>
        </div>
        <div className="bg-dark-card border border-dark-border rounded-lg p-6">
          <div className="flex items-center space-x-3 mb-2">
            <AlertTriangle className="w-5 h-5 text-high" />
            <h3 className="text-sm font-medium text-gray-400">Alerts Analyzed</h3>
          </div>
          <p className="text-3xl font-bold text-white">{report.alerts_count}</p>
        </div>
        <div className="bg-dark-card border border-dark-border rounded-lg p-6">
          <div className="flex items-center space-x-3 mb-2">
            <Server className="w-5 h-5 text-medium" />
            <h3 className="text-sm font-medium text-gray-400">Affected Hosts</h3>
          </div>
          <p className="text-3xl font-bold text-white">{report.hosts?.length || 0}</p>
        </div>
        <div className="bg-dark-card border border-dark-border rounded-lg p-6">
          <div className="flex items-center space-x-3 mb-2">
            <Clock className="w-5 h-5 text-info" />
            <h3 className="text-sm font-medium text-gray-400">Detection Time</h3>
          </div>
          <p className="text-sm font-semibold text-white">{formatDate(report.created_at)}</p>
        </div>
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column - 2/3 width */}
        <div className="lg:col-span-2 space-y-6">
          {/* Attack Timeline - AI Reconstructed */}
          {report.details?.timeline && report.details.timeline.length > 0 && (
            <div className="bg-dark-card border border-dark-border rounded-lg p-6">
              <div className="flex items-center space-x-3 mb-6">
                <TrendingUp className="w-5 h-5 text-info" />
                <h2 className="text-xl font-semibold text-white">
                  Attack Timeline (AI-Reconstructed)
                </h2>
              </div>
              <div className="space-y-4">
                {report.details.timeline.map((event, idx) => (
                  <div key={idx} className="flex space-x-4">
                    <div className="flex flex-col items-center">
                      <div className="w-3 h-3 rounded-full bg-info" />
                      {idx < report.details.timeline!.length - 1 && (
                        <div className="w-0.5 h-full bg-dark-border mt-2" />
                      )}
                    </div>
                    <div className="flex-1 pb-6">
                      <div className="bg-dark-surface border border-dark-border rounded-lg p-4">
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-sm font-mono text-gray-400">
                            {event.timestamp}
                          </span>
                          <span className="text-xs px-2 py-1 bg-info/10 text-info rounded">
                            {event.host}
                          </span>
                        </div>
                        <div className="mb-2">
                          <span className="text-sm font-semibold text-high mr-2">
                            {event.tactic}
                          </span>
                          <span className="text-sm text-gray-400">→</span>
                          <span className="text-sm font-mono text-medium ml-2">
                            {event.technique}
                          </span>
                        </div>
                        <p className="text-sm text-gray-300">{event.description}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* AI Predictions */}
          {report.details?.predictions && report.details.predictions.length > 0 && (
            <div className="bg-gradient-to-br from-high/10 to-high/5 border border-high/20 rounded-lg p-6">
              <div className="flex items-center space-x-3 mb-6">
                <Eye className="w-5 h-5 text-high" />
                <h2 className="text-xl font-semibold text-white">
                  AI-Predicted Next Actions
                </h2>
              </div>
              <div className="space-y-3">
                {report.details.predictions.map((pred, idx) => (
                  <div
                    key={idx}
                    className="bg-dark-card border border-dark-border rounded-lg p-4"
                  >
                    <div className="flex items-start space-x-3">
                      <div className="flex-shrink-0 px-3 py-1 bg-high/10 text-high rounded text-xs font-semibold">
                        {pred.confidence}
                      </div>
                      <div className="flex-1">
                        <p className="text-white font-medium mb-1">{pred.action}</p>
                        {pred.reasoning && (
                          <p className="text-sm text-gray-400">{pred.reasoning}</p>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Incident Response Workflow - AI-Generated Playbook */}
          {report.suggested_actions && (
            <div className="bg-dark-card border border-dark-border rounded-lg p-6">
              <div className="flex items-center space-x-3 mb-6">
                <Shield className="w-5 h-5 text-low" />
                <h2 className="text-xl font-semibold text-white">
                  AI-Generated Response Playbook
                </h2>
              </div>
              <div className="space-y-6">
                {['containment', 'eradication', 'recovery'].map((phase) => {
                  const actions = report.suggested_actions[phase as keyof typeof report.suggested_actions];
                  if (!actions || actions.length === 0) return null;

                  const phaseConfig = {
                    containment: { color: 'critical', icon: XCircle, label: 'Containment' },
                    eradication: { color: 'high', icon: AlertTriangle, label: 'Eradication' },
                    recovery: { color: 'low', icon: CheckCircle, label: 'Recovery' },
                  };

                  const config = phaseConfig[phase as keyof typeof phaseConfig];
                  const Icon = config.icon;

                  return (
                    <div key={phase}>
                      <div className="flex items-center space-x-2 mb-3">
                        <Icon className={`w-4 h-4 text-${config.color}`} />
                        <h3 className="text-sm font-semibold text-gray-300 uppercase tracking-wide">
                          {config.label}
                        </h3>
                      </div>
                      <ul className="space-y-2">
                        {actions.map((action, idx) => (
                          <li
                            key={idx}
                            className="flex items-start space-x-3 text-sm text-gray-300 bg-dark-surface border border-dark-border rounded-lg p-3"
                          >
                            <span className="flex-shrink-0 w-6 h-6 bg-dark-border rounded-full flex items-center justify-center text-xs font-semibold">
                              {idx + 1}
                            </span>
                            <span className="flex-1">
                              {typeof action === 'string' ? action : action.action}
                            </span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* Right Column - 1/3 width */}
        <div className="space-y-6">
          {/* MITRE ATT&CK Techniques */}
          {report.mitre_list && report.mitre_list.length > 0 && (
            <div className="bg-dark-card border border-dark-border rounded-lg p-6">
              <h2 className="text-lg font-semibold text-white mb-4">
                MITRE ATT&CK Techniques
              </h2>
              <div className="space-y-3">
                {report.mitre_list.map((mitre, idx) => (
                  <div
                    key={idx}
                    className="border border-dark-border rounded-lg p-3 hover:border-info/20 transition-colors"
                  >
                    <div className="flex items-center justify-between mb-2">
                      <span className="font-mono text-sm font-semibold text-info">
                        {mitre.technique_id}
                      </span>
                      <span className="text-xs px-2 py-1 bg-medium/10 text-medium rounded">
                        {mitre.tactic}
                      </span>
                    </div>
                    <p className="text-sm text-gray-300">{mitre.technique_name}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Indicators of Compromise (IOCs) */}
          {report.iocs && (
            <div className="bg-dark-card border border-dark-border rounded-lg p-6">
              <h2 className="text-lg font-semibold text-white mb-4">
                Indicators of Compromise
              </h2>
              <div className="space-y-4">
                {Object.entries(report.iocs).map(([key, values]) => {
                  if (!values || values.length === 0) return null;
                  return (
                    <div key={key}>
                      <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                        {key.replace('_', ' ')}
                      </h3>
                      <div className="space-y-1">
                        {values.slice(0, 5).map((value: string, idx: number) => (
                          <div
                            key={idx}
                            className="text-sm font-mono bg-dark-surface border border-dark-border rounded px-3 py-2 text-gray-300"
                          >
                            {value}
                          </div>
                        ))}
                        {values.length > 5 && (
                          <p className="text-xs text-gray-500 mt-2">
                            +{values.length - 5} more
                          </p>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Business Impact Assessment */}
          {report.details?.business_impact && (
            <div className="bg-dark-card border border-dark-border rounded-lg p-6">
              <div className="flex items-center space-x-3 mb-4">
                <Lightbulb className="w-5 h-5 text-medium" />
                <h2 className="text-lg font-semibold text-white">Business Impact</h2>
              </div>
              <div className="space-y-3 text-sm">
                {report.details.business_impact.operational_risk && (
                  <div>
                    <span className="text-gray-400">Operational Risk:</span>
                    <p className="text-white mt-1">{report.details.business_impact.operational_risk}</p>
                  </div>
                )}
                {report.details.business_impact.data_integrity_risk && (
                  <div>
                    <span className="text-gray-400">Data Integrity Risk:</span>
                    <p className="text-white mt-1">{report.details.business_impact.data_integrity_risk}</p>
                  </div>
                )}
                {report.details.business_impact.domain_wide_risk && (
                  <div>
                    <span className="text-gray-400">Domain-Wide Risk:</span>
                    <p className="text-white mt-1">{report.details.business_impact.domain_wide_risk}</p>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Affected Systems */}
          <div className="bg-dark-card border border-dark-border rounded-lg p-6">
            <h2 className="text-lg font-semibold text-white mb-4">Affected Systems</h2>
            <div className="space-y-3">
              <div>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                  Hosts
                </h3>
                <div className="flex flex-wrap gap-2">
                  {report.hosts?.map((host, idx) => (
                    <span
                      key={idx}
                      className="px-3 py-1 bg-dark-surface border border-dark-border rounded-lg text-sm text-gray-300"
                    >
                      {host}
                    </span>
                  ))}
                </div>
              </div>
              {report.agents && report.agents.length > 0 && (
                <div>
                  <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                    Agent IDs
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {report.agents.map((agent, idx) => (
                      <span
                        key={idx}
                        className="px-3 py-1 bg-dark-surface border border-dark-border rounded-lg text-sm font-mono text-gray-300"
                      >
                        {agent}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
