import { Brain, AlertTriangle } from 'lucide-react';
import { getRiskScoreColor, getSeverityColor } from '@/lib/utils';
import type { ThreatReport } from '@/types';

interface ExecutiveSummaryProps {
  report: ThreatReport;
}

export default function ExecutiveSummary({ report }: ExecutiveSummaryProps) {
  const tldr = report.details?.tldr || report.summary || 'AI analysis in progress...';

  return (
    <div className="relative overflow-hidden bg-gradient-to-br from-dark-card via-dark-surface to-dark-card border-2 border-info/30 rounded-xl p-8 shadow-2xl">
      {/* Animated Background Pattern */}
      <div className="absolute inset-0 opacity-5">
        <div className="absolute inset-0" style={{
          backgroundImage: `radial-gradient(circle at 2px 2px, rgba(6, 182, 212, 0.15) 1px, transparent 0)`,
          backgroundSize: '32px 32px'
        }} />
      </div>

      <div className="relative z-10">
        {/* Header */}
        <div className="flex items-start justify-between mb-6">
          <div className="flex items-center space-x-4">
            <div className="p-3 bg-info/10 border border-info/30 rounded-xl">
              <Brain className="w-8 h-8 text-info" />
            </div>
            <div>
              <div className="flex items-center space-x-3">
                <h2 className="text-2xl font-bold text-white">AI Executive Summary</h2>
                <span className="px-3 py-1 bg-info/20 border border-info/40 rounded-full text-xs font-semibold text-info">
                  RAG-Powered Analysis
                </span>
              </div>
              <p className="text-sm text-gray-400 mt-1">Generated by LLM with threat intelligence context</p>
            </div>
          </div>

          {/* Risk Score Badge */}
          <div className="flex flex-col items-center">
            <div className={`text-6xl font-black ${getRiskScoreColor(report.risk_score)} drop-shadow-lg`}>
              {report.risk_score}
            </div>
            <div className="text-xs text-gray-400 mt-1">Risk Score</div>
            <div className={`mt-2 px-4 py-1 rounded-lg border ${getSeverityColor(report.severity)}`}>
              <span className="text-sm font-semibold">{report.severity}</span>
            </div>
          </div>
        </div>

        {/* Summary Text */}
        <div className="bg-dark-bg/50 border border-dark-border rounded-lg p-6 mb-6">
          <div className="flex items-start space-x-3">
            <AlertTriangle className="w-5 h-5 text-high flex-shrink-0 mt-1" />
            <p className="text-lg leading-relaxed text-gray-100 font-medium">
              {tldr}
            </p>
          </div>
        </div>

        {/* Quick Stats Bar */}
        <div className="grid grid-cols-4 gap-4">
          <div className="bg-dark-bg/30 border border-dark-border rounded-lg p-4">
            <div className="text-2xl font-bold text-white">{report.alerts_count}</div>
            <div className="text-xs text-gray-400 mt-1">Alerts Analyzed</div>
          </div>
          <div className="bg-dark-bg/30 border border-dark-border rounded-lg p-4">
            <div className="text-2xl font-bold text-white">{report.hosts?.length || 0}</div>
            <div className="text-xs text-gray-400 mt-1">Affected Hosts</div>
          </div>
          <div className="bg-dark-bg/30 border border-dark-border rounded-lg p-4">
            <div className="text-2xl font-bold text-white">{report.mitre_list?.length || 0}</div>
            <div className="text-xs text-gray-400 mt-1">MITRE Techniques</div>
          </div>
          <div className="bg-dark-bg/30 border border-dark-border rounded-lg p-4">
            <div className="text-2xl font-bold text-info">
              {new Date(report.created_at).toLocaleDateString()}
            </div>
            <div className="text-xs text-gray-400 mt-1">Detection Date</div>
          </div>
        </div>
      </div>
    </div>
  );
}
