import { Brain, AlertTriangle } from 'lucide-react';
import { getRiskScoreColor, getSeverityColor } from '@/lib/utils';
import type { ThreatReport } from '@/types';

interface ExecutiveSummaryProps {
  report: ThreatReport;
}

export default function ExecutiveSummary({ report }: ExecutiveSummaryProps) {
  const tldr = report.details?.tldr || report.summary || 'AI analysis in progress...';

  return (
    <div className="bg-white border-2 border-neutral-300 p-8">
      <div>
        {/* Header */}
        <div className="flex items-start justify-between mb-6 pb-6 border-b border-neutral-300">
          <div className="flex items-center space-x-4">
            <div className="p-3 bg-info-light border-2 border-info">
              <Brain className="w-8 h-8 text-info" />
            </div>
            <div>
              <div className="flex items-center space-x-3">
                <h2 className="text-2xl font-medium text-neutral-900">#{report.id} Report Summary</h2>
                <span className="px-3 py-1 bg-info-light text-info-dark border border-info text-xs font-bold">
                  RAG Analysis
                </span>
              </div>
              <p className="text-sm text-neutral-700 font-medium mt-1">Generated by LLM with threat intelligence context</p>
            </div>
          </div>

          {/* Risk Score Badge */}
          <div className="flex flex-col items-center">
            <div className={`text-6xl font-light ${getRiskScoreColor(report.risk_score)}`}>
              {report.risk_score}
            </div>
            <div className="text-xs text-neutral-700 font-medium mt-1">Risk Score</div>
            <div className={`mt-2 px-4 py-1 border ${getSeverityColor(report.severity)}`}>
              <span className="text-sm font-semibold">{report.severity}</span>
            </div>
          </div>
        </div>

        {/* Summary Text */}
        <div className="bg-neutral-50 border border-neutral-300 p-6 mb-6">
          <div className="flex items-start space-x-3">
            <AlertTriangle className="w-5 h-5 text-high flex-shrink-0 mt-1" />
            <p className="text-lg leading-relaxed text-neutral-900 font-medium">
              {tldr}
            </p>
          </div>
        </div>

        {/* Quick Stats Bar */}
        <div className="grid grid-cols-4 gap-4">
          <div className="bg-neutral-50 border border-neutral-300 p-4">
            <div className="text-2xl font-medium text-neutral-900">{report.alerts_count}</div>
            <div className="text-xs text-neutral-700 font-medium mt-1">Alerts Analyzed</div>
          </div>
          <div className="bg-neutral-50 border border-neutral-300 p-4">
            <div className="text-2xl font-medium text-neutral-900">{report.hosts?.length || 0}</div>
            <div className="text-xs text-neutral-700 font-medium mt-1">Affected Hosts</div>
          </div>
          <div className="bg-neutral-50 border border-neutral-300 p-4">
            <div className="text-2xl font-medium text-neutral-900">{report.mitre_list?.length || 0}</div>
            <div className="text-xs text-neutral-700 font-medium mt-1">MITRE Techniques</div>
          </div>
          <div className="bg-neutral-50 border border-neutral-300 p-4">
            <div className="text-2xl font-medium text-info">
              {new Date(report.created_at).toLocaleDateString()}
            </div>
            <div className="text-xs text-neutral-700 font-medium mt-1">Detection Date</div>
          </div>
        </div>
      </div>
    </div>
  );
}
